version: '2'

services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/peerOrg1-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/64f98e3c73e7af043d1b04ce37ddc9ad624bc5577d86693c71836a486d2381d9_sk -b admin:adminpw' -d
    volumes:
      - ./crypto/ca_org1:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_org1

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/peerOrg2-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/53c5a4cba1e591d94b8c8628015a95752d502706fc9d0915b120c7047afbb17f_sk -b admin2:adminpw2' -d
    volumes:
      - ./crypto/ca_org2:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_org2

  orderer0:
    container_name: orderer0
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/localMspConfig
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./crypto/orderer:/var/hyperledger/orderer
    ports:
      - 7050:7050

  peer1:
    container_name: peer1
    extends:
      file: peer-base/peer-base-no-tls.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1:7051
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto/peer/peer1/localMspConfig:/etc/hyperledger/fabric/msp/sampleconfig
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer0

  peer2:
    container_name: peer2
    extends:
      file: peer-base/peer-base-no-tls.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto/peer/peer2/localMspConfig:/etc/hyperledger/fabric/msp/sampleconfig
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
      - orderer0
      - peer1

  peer3:
    container_name: peer3
    extends:
      file: peer-base/peer-base-no-tls.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer3
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3:7051
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto/peer/peer3/localMspConfig:/etc/hyperledger/fabric/msp/sampleconfig
    ports:
      - 9051:7051
      - 9053:7053
    depends_on:
      - orderer0
      - peer1
      - peer2

  peer4:
    container_name: peer4
    extends:
      file: peer-base/peer-base-no-tls.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer4
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer3:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto/peer/peer4/localMspConfig:/etc/hyperledger/fabric/msp/sampleconfig
    ports:
      - 10051:7051
      - 10053:7053
    depends_on:
      - orderer0
      - peer1
      - peer2
      - peer3

  cli:
    container_name: cli
    image: hyperledger/fabric-peer
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_NEXT=true
      - CORE_PEER_ID=cli
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_ADDRESS=peer1:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/setup-marbles.sh ${CHANNEL_NAME}; bash'
    volumes:
        - /var/run/:/host/var/run/
        - ./examples/:/opt/gopath/src/github.com/hyperledger/fabric/examples/
        - ./crypto:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - orderer0
      - peer1
      - peer2
      - peer3
      - peer4
