version: '2'

services:

  mtc-01:
    build: ${MARBLES_LOCATION}/
    image: marbles
    depends_on:
      - peer-01
      - orderer-01
      - cop-01
    links:
      - cop-01
      - orderer-01
      - peer-02
    ports:
      - 3000:3000
    volumes:
      - ${CREDS_LOCATION}/blockchain_creds1.json:/app/marbles1.json
      - ${CREDS_LOCATION}/keyValStore-1:/app/keyValStore-asdf
    container_name: united_marbles
    entrypoint: gulp united_marbles

  mtc-02:
    build: ${MARBLES_LOCATION}/
    image: marbles
    depends_on:
      - peer-01
      - orderer-01
      - cop-01
    links:
      - cop-01
      - orderer-01
      - peer-03
    ports:
      - 3001:3000
    volumes:
      - ${CREDS_LOCATION}/blockchain_creds2.json:/app/marbles2.json
      - ${CREDS_LOCATION}/keyValStore-2:/app/keyValStore-asdf
    container_name: marble_market
    entrypoint: gulp marble_market


